server:
  port: 8888
spring:
  application:
    name: erudio-config-server
  cloud:
     config:
       server:
         git:
            uri: https://github.com/jpaulo2710/erudio-config-server
            #username: username
            #password: password
            default-label: master
            search-paths:
              - 'greeting-service*'
